export const TAG_INFO: Record<string, string> = {
  traveler: 'Primarily travels and explores places, may or may not shoot photos seriously.',
  photographer: 'Focused on photography as the primary craft — travel is often in service of the shot.',
  both: 'Equally invested in traveling and photography, where the journey and the shot matter equally.',
  Backpacker: 'Travels light and on a budget, favoring hostels, local transport, and flexible plans.',
  Luxury: 'Prefers comfort — quality stays, private transport, curated experiences.',
  Solo: 'Prefers traveling independently, exploring at their own pace.',
  Family: 'Travels with family, planning around group comfort and shared experiences.',
  'Weekend Trips': 'Sticks to short getaways, usually within a few hours of home.',
  Mountains: 'Drawn to high-altitude landscapes, treks, and peaks.',
  Beaches: 'Loves coastal spots, oceans, and beach towns.',
  City: 'Enjoys urban exploration — architecture, streets, city life.',
  Hills: 'Prefers hill stations and rolling countryside over extreme altitude.',
  Desert: 'Drawn to arid landscapes and desert scenery.',
  Forest: 'Loves dense greenery, national parks, and forest trails.',
  Islands: 'Seeks out island destinations and remote coastal escapes.',
  Countryside: 'Prefers quiet rural landscapes over cities.',
  'Historical Sites': 'Drawn to heritage sites, monuments, and history-rich locations.',
  'Wildlife Safari': 'Travels to see and photograph wildlife in its natural habitat.',
  Street: 'Candid photography of everyday life in public spaces.',
  Landscape: 'Wide scenic shots of natural or urban environments.',
  Portrait: 'Photography focused on people and expression.',
  Astro: 'Night-sky photography — stars, the Milky Way, celestial events.',
  Wildlife: 'Photographing animals in their natural environment.',
  Architecture: 'Focused on buildings, structures, and man-made design.',
  Travel: 'General documentation of places and journeys.',
  Macro: 'Extreme close-up photography of small subjects.',
  Aerial: 'Shots taken from drones or elevated viewpoints.',
  'Long Exposure': 'Uses slow shutter speeds to capture motion — light trails, water, clouds.',
  'Black & White': 'Monochrome photography, focused on tone and contrast.',
  Night: 'Photography after dark — city lights, low-light scenes.',
  Urban: 'City and street-level scenes, often architecture-adjacent.',
  Nature: 'Broad nature photography — plants, landscapes, natural detail.',
  Minimalist: 'Simple compositions with few elements and negative space.',
  Documentary: 'Storytelling-focused, capturing real events and life as it happens.',
  Abstract: 'Focused on shape, color, and pattern over literal subjects.',
};